<a href="https://colab.research.google.com/github/YonggunJung/Fastcompus/blob/main/04_06_tensor_manipulations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Tensor Manipulations

In [ ]:
import torch

## Tensor Shaping

### reshape: Change Tensor Shape

In [ ]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])

print(x.size())

torch.Size([3, 2, 2])


In [ ]:
print(x.reshape(12)) # 12 = 3 * 2 * 2
print(x.reshape(-1)) # -1은 일단 알아서 해줘 라는 뜻

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [ ]:
print(x.reshape(3, 4)) # 3 * 4 = 3 * 2 * 2
print(x.reshape(3, -1)) # 3행을 만들건데 열은 니가 알아서해 넣어줘(딱 들어 맞지 않을 경우는 에러남)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [ ]:
print(x.reshape(3, 1, 4))
print(x.reshape(-1, 1, 4))

tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [ ]:
print(x.reshape(3, 2, 2, 1))

tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]],

         [[11.],
          [12.]]]])


You can use 'view()' instead of 'reshape()' in some cases.

- https://pytorch.org/docs/stable/tensor_view.html
- https://pytorch.org/docs/stable/tensors.html?highlight=view#torch.Tensor.view

### squeeze: Remove dimension which has only one element.

In [ ]:
# squeeze : 쥐어 짜다
# 어떤 차원에 1이 있으면 짜버린다
# 차원 축소 하는 것
x = torch.FloatTensor([[[1, 2],
                        [3, 4]]])
print(x.size())

torch.Size([1, 2, 2])


Remove any dimension which has only one element.

In [ ]:
# 만약 1이 없으면 그대로 출력 된다. 아무일도 일어나지 않는다
print(x.squeeze())
print(x.squeeze().size())
# torch.Size([1, 2, 2]) 이게 rch.Size([2, 2]) 이렇게 됐음

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])


Remove certain dimension, if it has only one element.
If it is not, there would be no change.

In [ ]:
# 특정 차원 스퀴즈 가능
print(x.squeeze(0).size())  # 여기는 0번째에 1이 있어서 스퀴즈함
print(x.squeeze(1).size())  # 여기는 1번째에 1이 없어서 스퀴즈 못함

torch.Size([2, 2])
torch.Size([1, 2, 2])


### unsqueeze: Insert dimension at certain index.

In [ ]:
# 차원 늘리는 것
x = torch.FloatTensor([[1, 2],
                       [3, 4]])
print(x.size())

torch.Size([2, 2])


In [ ]:
# 이 셋다 똑같은 코드
print(x.unsqueeze(2))
print(x.unsqueeze(-1))
print(x.reshape(2, 2, -1))

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
